language: node_js
node_js:
- '8'
- '10'
before_install: sudo apt-get install libcairo2-dev libjpeg8-dev libpango1.0-dev libgif-dev build-essential g++
before_script:
  - export CHROME_BIN=chromium-browser
script:
- yarn build
- yarn test
cache: yarn
